name: Compile test

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Compile source code test
        run: |
          ./shell/build_test_ci.sh
      - name: Run unit tests
        run: |
          ./judge_tests
      - name: Build real compile/run tests
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          cmake -DENABLE_TESTS=ON -DENABLE_REAL_TESTS=ON .
          make -j$(nproc) judge_real_tests
      - name: Run real compile/run tests
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          ./judge_real_tests
